// Generated by typings
// Source: scripts/TypeLite.Net4.d.ts
declare module Models {
	interface List {
		Count: number;
		CountEnded: number;
		Id: number;
		Name: string;
		Tasks: Models.Task[];
	}
	interface Task {
		Ended: boolean;
		Id: number;
		ListId: number;
		Name: string;
    }
    interface Chat {
        Id: number;
        Message: string;
        Type: string;
        Suggestions: string[];
        ContextID: string;
        ContentType: string;
        LinkedChatID: string;
        AuthToken: string;
    }
    enum ContentTypes {
        text,
        image,
        date,
        hyperlink,
        html
    }
}
declare module Models.ViewModel {
	interface JSONReturnVM<T> {
		element: T;
		errormessage: string;
		haserror: boolean;
	}
}